### ISSUE TITLE
Just unescape 5 special tags?

### ISSUE THREAD

**Issue by herlon214** [ForbesLindesay/unescape-html#1]
This lib is just a test?

**Comment by ForbesLindesay** [comment]
This is specifically the reverse of https://github.com/component/escape-html.  It is intended to be light weight and compact so it can be used client side, so it only unescapes the characters that you should have escaped (in order to secure your application against script injection).  i.e. you don't need to escape any other tags.

If you need a full html-decoder.  I recommend using [he](https://github.com/mathiasbynens/he)

**Comment by herlon214** [comment]
Thanks @ForbesLindesay.
